Repository algo-plus/algo-plus, pull requests merged in 2024-05, with the labels that each got.

#4 Chore: 이미지 경로 수정
  package-lock.json
  src/baekjoon/containers/InfoModal/InfoModal.tsx
  src/oauth/authorize.js
  src/oauth/oauth2.js
Labels: enhancement

#7 status.tsx 코드 리팩토링
  src/baekjoon/scripts/status.css
  src/baekjoon/scripts/status.tsx
Labels: review note

#26 !HOTFIX: 정답을 맞췄을 때 '틀렸습니다' 모달이 발생하는 오류 해결
  src/baekjoon/scripts/status.tsx
Labels: bug, problem solving
