Repository algo-plus/algo-plus, pull requests merged in 2024-06, with the labels that each got.

#29 깃허브 연동 버그 수정
  public/css/link.css
  src/oauth/link.js
  src/oauth/oauth2.js
Labels: bug, enhancement

#30 오답 코드 순서 변경
  src/baekjoon/containers/ReviewModal/ReviewModal.css
  src/baekjoon/containers/ReviewModal/ReviewModal.tsx
  src/baekjoon/utils/uploadfunctions.ts
Labels: enhancement, review note

#31 코드 에디터 언어 기본값 설정 기능 구현
  src/baekjoon/components/LanguageSelectBox/LanguageSelectBox.tsx
  src/baekjoon/containers/SolveView/SolveView.tsx
  src/baekjoon/utils/storage/editor.ts
Labels: enhancement

#34 오답노트 레포지토리 캐시 확인
  src/baekjoon/scripts/status.tsx
  src/common/utils/storage.ts
Labels: bug, enhancement
